export const SONGS = [
		{ name: 'Overture', file: '1-overture' },
		{ name: 'Bedford Falls', file: '2-bedford' },
		{ name: 'Think Big', file: '3-thinkbig' },
		{ name: 'Charleston', file: '5-charleston' },
		{ name: 'This Old House', file: '6-house' },
		{ name: 'Trouble', file: '7-trouble' },
		{ name: 'I Forget', file: '8-forget' },
		{ name: 'Open Your Eyes', file: '9-eyes' },
		{ name: 'Our Last Dollars', file: '11-dollars' },
		{ name: 'Oahu Wahoo', file: '12-oahu' },
		{ name: 'E Mangia', file: '14-mangia' },
		{ name: "You're Hired", file: '15-hired' },
		{ name: "Can't Keep the Bailey Boys Down", file: '17-boys' },
		{ name: 'Your White Knight', file: '18-knight' },
		{ name: 'Angel Gets His Wings', file: '20-wings' },
		{ name: "It's a Wonderful Life", file: '22-iawl' },
		{ name: 'Christmas Day', file: '25-christmasday' },
	]